# TODO: add targets for generating eps files
# TODO: add target for generating paper

clean:
	rm -rf auto
	rm -rf *.aux
	rm -rf *.bbl
	rm -rf *.blg
	rm -rf *.eps
	rm -rf *.log
	rm -rf *.out
	rm -rf *.pdf
	rm -rf *.pdf_tex
